language: scala
scala:
  - 2.12.8
sudo: required
dist: trusty

matrix:
  include:
    - stage: build
      jdk: oraclejdk8

script:
  - sbt clean coverage test coverageReport codacyCoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)